<?php require('template/header.phtml') ?>

    <h2>About the company Charger EVs</h2>
    <p>This website was planned and developed to join people from all around the world.</p>
    <p>Allowing everyone with an EV to communicate and further their travels.</p>

    <h3>What We Offer</h3>
    <p>GLOBAL EVs pave the path towards a future which can be more sustainable than the one we have today.
    Our main goal is to fight for the resources of this planet by allowing for more renewable energy.</p>

<?php require('template/footer.phtml') ?>