<?php require('template/header.phtml') ?>
    <!-- tag above implements the reusable header.phtml file -->

    <h2>Welcome to Borrow My Charger!</h2>
    <p class="lead">This website was created to provide the service of paving a way for the era of EV stations being borrowed to other users of Electric Vehicles</p>

    <h3>Moving Forward</h3>
    <p>You may now use our website to find and communicate with owners of different EV charge-points to aid your journey with your own EV!</p>

    <h3>What to Expect in the Near Future</h3>
    <p>We are currently working on improvements to the website such as the following:</p>
    <ul>
        <li>Register and begin the verification process to listing a charge-point without the help of admin</li>
        <li>Direct Messaging between you and a charge-point owner, hosted on the website</li>
        <li><mark>And Much More!</mark></li>
    </ul>

    <h3>Marking Scheme</h3>
    <h4>Assessment 1 - Back-end Focus</h4>
    <a href="assessmentCriteria1.php">Click here to view my Marking Scheme!</a>

    <h4><br>Assessment 2 - Front-end Focus</h4>
    <a href="assessmentCriteria2.php">Click here to view my Marking Scheme!</a>
<?php require('template/footer.phtml') ?>