<!-- closing tags which connect to the header.phtml file, once both are implemented in one page -->
<br><br><br><br><br>

</section>
</div>
</div>
</main>

<!-- footer element to span across the bottom of the page -->
<footer class="footer fixed-bottom mt-auto py-3 bg-dark text-white">
    <div class="container">
        <span class="text-muted">Allowing people across the globe to communicate with others and their EVs, since 2022!</span>
    </div>
</footer>


<!-- Positioned at the end of a page for faster loading times -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>