<!DOCTYPE html>

<html lang="en">
<head>
    <!-- Browser meta data -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Borrow My Charger - <?php echo $view->pageTitle; ?></title>
    <!-- Personal details for the project stated below -->
    <meta name="description - Created as per Required University Module Assessment">
    <meta name="author - M Hajas">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="css/general.css" rel="stylesheet">
</head>

<body class="d-flex flex-column h-100">
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-secondary text-white">
            <div class="container-fluid">
                <a class="navbar-brand">GLOBAL EVs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">

                        <?php
                        if (isset($_SESSION['username'])) {
                        ?>

                        <li class="nav-item dropdown">
                            <?php if (isset($_SESSION['username'])) { ?>
                                <a class="nav-link" href="index.php">Logout</a>
                            <?php } else { ?>
                                <a class="nav-link" href="index.php">Login</a>
                            <?php } ?>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="homepage.php">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="chargersData.php">Charger Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="about.php">About</a>
                        </li>

                        <?php
                        } else {
                        ?>

                            <li class="nav-item dropdown">
                                <?php if (isset($_SESSION['username'])) { ?>
                                    <a class="nav-link" href="index.php">Logout</a>
                                <?php } else { ?>
                                    <a class="nav-link" href="index.php">Login</a>
                                <?php } ?>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="homepage.php">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="about.php">About</a>
                            </li>

                        <?php } ?>

                    </ul>
                </div>
            </div>
        </nav>
    </header>


<!-- Begin page content -->
    <main class="flex-shrink-0">
        <div class="container">
            <div  class="row">
                <div id="title" class="col-xs-12">
                    <br><br>
                    <img class="pt-1 pb-3" src="images/EVsLogo.svg" alt="Global EVs Logo" width="250" height="250"/>
                    <h1><?php echo $view->pageTitle ?> </h1>
                </div>
            </div>

            <!-- opening tags which later connect to the footer.phtml tags, once connected via same page -->
            <div class="row">
                <section id="content" class="col-xs-12 col-sm-12 col-md-12">



